//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSB_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateContractor
    {
        public int private_contractor_id { get; set; }
        public string private_contractor_name { get; set; }
        public string private_contractor_email { get; set; }
    }
}
