//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSB_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSBDiary
    {
        public int id { get; set; }
        public string jurisdiction { get; set; }
        public string case_name { get; set; }
        public string case_no { get; set; }
        public Nullable<System.DateTime> hearing_date { get; set; }
        public string judge { get; set; }
        public Nullable<int> transcript_particular_type_id { get; set; }
        public Nullable<int> is_daily { get; set; }
        public Nullable<int> sound_type_id { get; set; }
        public Nullable<int> sound_centre_id { get; set; }
        public Nullable<int> transcript_copy_type_id { get; set; }
        public Nullable<System.DateTime> tr_cancelled_date { get; set; }
        public Nullable<System.DateTime> level8_copy_date { get; set; }
        public string completed_by_name { get; set; }
        public Nullable<int> actual_num_of_pages { get; set; }
        public Nullable<int> estimated_num_of_pages { get; set; }
        public string reporters_list { get; set; }
        public Nullable<int> private_contractor_id { get; set; }
        public Nullable<int> is_handed_down { get; set; }
        public string comments { get; set; }
        public string cancel_reason { get; set; }
    }
}
