//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSB_SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptCopyType
    {
        public int transcript_copy_type_id { get; set; }
        public string transcript_copy_type { get; set; }
    }
}
